
    name: 24/7 Rain Stream
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - run: ffmpeg -re -stream_loop -1 -i "https://docs.google.com/uc?export=download&id=1eX-aF1nYWLa8hlTdSBVuX9_t3T3RUYNM" -c:v libx264 -preset veryfast -b:v 3000k -pix_fmt yuv420p -c:a aac -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
      
